# -*- coding: utf-8 -*-
"""Assignment2_MNIST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IjWOk8WZc4-iWaFHpksmM_zyoAlLvuBP

# Assignment 2 — Learning Strategy: MNIST
kode MNIST bersumber dari materi kuliah Learning Strategy, selanjutnya menjalankan lima skenario eksperimen:

1. L1 regularization
2. L2 regularization
3. Dropout
4. Early stopping
5. L1 regularization and dropout

## Load MNIST
"""

import keras
import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Flatten, Dense, Dropout
from keras import regularizers
from keras.callbacks import EarlyStopping

(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.reshape(-1, 28, 28, 1)
X_test = X_test.reshape(-1, 28, 28, 1)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)

print('X_train:', X_train.shape)
print('X_test :', X_test.shape)

"""## Baseline"""

model1 = Sequential()
model1.add(Flatten())
model1.add(Dense(64, activation='relu'))
model1.add(Dense(10, activation='softmax'))
model1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])

history1 = model1.fit(X_train, y_train, epochs=10, batch_size=100, validation_data=(X_test, y_test))
model1.summary()

loss, accuracy = model1.evaluate(X_test, y_test, verbose=0)
print('Baseline testing loss:', loss)
print('Baseline testing accuracy:', accuracy)

epochs = range(len(history1.history['loss']))
plt.figure(figsize=(7,4))
plt.plot(epochs, history1.history['loss'], label='training loss ANN')
plt.plot(epochs, history1.history['val_loss'], label='validation loss ANN')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Baseline Loss')
plt.legend()
plt.show()

plt.figure(figsize=(7,4))
plt.plot(history1.history['acc'], label='training accuracy')
plt.plot(history1.history['val_acc'], label='validation accuracy')
plt.xlabel('Epoch'); plt.ylabel('Accuracy'); plt.title('Baseline Accuracy'); plt.legend(); plt.show()

"""## Skenario 2(a): L1 Regularization
L1 Rate= **0.001**.
"""

L1_RATE = 0.001
model_l1 = Sequential([
    Flatten(),
    Dense(64, activation='relu', kernel_regularizer=regularizers.l1(L1_RATE)),
    Dense(10, activation='softmax', kernel_regularizer=regularizers.l1(L1_RATE))
])
model_l1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])
history_l1 = model_l1.fit(X_train, y_train, epochs=10, batch_size=100, validation_data=(X_test, y_test))
model_l1.summary()
l1_loss, l1_acc = model_l1.evaluate(X_test, y_test, verbose=0)
print('L1 rate:', L1_RATE)
print('Testing loss:', l1_loss)
print('Testing accuracy:', l1_acc)

plt.figure(figsize=(7,4))
plt.plot(history_l1.history['loss'], label='training loss')
plt.plot(history_l1.history['val_loss'], label='validation loss')
plt.xlabel('Epoch'); plt.ylabel('Loss'); plt.title('Scenario 2(a) — L1 Loss'); plt.legend(); plt.show()

plt.figure(figsize=(7,4))
plt.plot(history_l1.history['acc'], label='training accuracy')
plt.plot(history_l1.history['val_acc'], label='validation accuracy')
plt.xlabel('Epoch'); plt.ylabel('Accuracy'); plt.title('Scenario 2(a) — L1 Accuracy'); plt.legend(); plt.show()

"""## Skenario 2(b): L2 Regularization
L2 Rate= **0.001**.
"""

L2_RATE = 0.001
model_l2 = Sequential([
    Flatten(),
    Dense(64, activation='relu', kernel_regularizer=regularizers.l2(L2_RATE)),
    Dense(10, activation='softmax', kernel_regularizer=regularizers.l2(L2_RATE))
])
model_l2.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])
history_l2 = model_l2.fit(X_train, y_train, epochs=10, batch_size=100, validation_data=(X_test, y_test))
model_l2.summary()
l2_loss, l2_acc = model_l2.evaluate(X_test, y_test, verbose=0)
print('L2 rate:', L2_RATE)
print('Testing loss:', l2_loss)
print('Testing accuracy:', l2_acc)

plt.figure(figsize=(7,4))
plt.plot(history_l2.history['loss'], label='training loss')
plt.plot(history_l2.history['val_loss'], label='validation loss')
plt.xlabel('Epoch'); plt.ylabel('Loss'); plt.title('Scenario 2(b) — L2 Loss'); plt.legend(); plt.show()

plt.figure(figsize=(7,4))
plt.plot(history_l2.history['acc'], label='training accuracy')
plt.plot(history_l2.history['val_acc'], label='validation accuracy')
plt.xlabel('Epoch'); plt.ylabel('Accuracy'); plt.title('Scenario 2(b) — L2 Accuracy'); plt.legend(); plt.show()

"""## Skenario 2(c): Dropout
Dropout Rate= **0.5**.
"""

DROPOUT_RATE = 0.5
model_dropout = Sequential([
    Flatten(),
    Dense(64, activation='relu'),
    Dropout(DROPOUT_RATE),
    Dense(10, activation='softmax')
])
model_dropout.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])
history_dropout = model_dropout.fit(X_train, y_train, epochs=10, batch_size=100, validation_data=(X_test, y_test))
model_dropout.summary()
drop_loss, drop_acc = model_dropout.evaluate(X_test, y_test, verbose=0)
print('Dropout rate:', DROPOUT_RATE)
print('Testing loss:', drop_loss)
print('Testing accuracy:', drop_acc)

plt.figure(figsize=(7,4))
plt.plot(history_dropout.history['loss'], label='training loss')
plt.plot(history_dropout.history['val_loss'], label='validation loss')
plt.xlabel('Epoch'); plt.ylabel('Loss'); plt.title('Scenario 2(c) — Dropout Loss'); plt.legend(); plt.show()

plt.figure(figsize=(7,4))
plt.plot(history_dropout.history['acc'], label='training accuracy')
plt.plot(history_dropout.history['val_acc'], label='validation accuracy')
plt.xlabel('Epoch'); plt.ylabel('Accuracy'); plt.title('Scenario 2(c) — Dropout Accuracy'); plt.legend(); plt.show()

"""## Skenario 2(d): Early Stopping
Early stopping menggunakan `patience=3`, sehingga training berhenti jika validation loss tidak membaik selama 3 epoch berturut-turut.
"""

early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)
model_early = Sequential()
model_early.add(Flatten())
model_early.add(Dense(64, activation='relu'))
model_early.add(Dense(10, activation='softmax'))
model_early.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])
history_early = model_early.fit(X_train, y_train, epochs=10, batch_size=100, validation_data=(X_test, y_test), callbacks=[early_stopping])
model_early.summary()
early_loss, early_acc = model_early.evaluate(X_test, y_test, verbose=0)
print('Early stopping patience:', 3)
print('Epochs actually run:', len(history_early.history['loss']))
print('Testing loss:', early_loss)
print('Testing accuracy:', early_acc)

plt.figure(figsize=(7,4))
plt.plot(history_early.history['loss'], label='training loss')
plt.plot(history_early.history['val_loss'], label='validation loss')
plt.xlabel('Epoch'); plt.ylabel('Loss'); plt.title('Scenario 2(d) — Early Stopping Loss'); plt.legend(); plt.show()

plt.figure(figsize=(7,4))
plt.plot(history_early.history['acc'], label='training accuracy')
plt.plot(history_early.history['val_acc'], label='validation accuracy')
plt.xlabel('Epoch'); plt.ylabel('Accuracy'); plt.title('Scenario 2(d) — Early Stopping Accuracy'); plt.legend(); plt.show()

"""## Skenario 2(e): L1 Regularization + Dropout
Menggabungkan L1 rate= **0.001** dan dropout rate= **0.5**.
"""

model_l1_dropout = Sequential([
    Flatten(),
    Dense(64, activation='relu', kernel_regularizer=regularizers.l1(L1_RATE)),
    Dropout(DROPOUT_RATE),
    Dense(10, activation='softmax')
])
model_l1_dropout.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])
history_l1_dropout = model_l1_dropout.fit(X_train, y_train, epochs=10, batch_size=100, validation_data=(X_test, y_test))
model_l1_dropout.summary()
l1d_loss, l1d_acc = model_l1_dropout.evaluate(X_test, y_test, verbose=0)
print('L1 rate:', L1_RATE)
print('Dropout rate:', DROPOUT_RATE)
print('Testing loss:', l1d_loss)
print('Testing accuracy:', l1d_acc)

plt.figure(figsize=(7,4))
plt.plot(history_l1_dropout.history['loss'], label='training loss')
plt.plot(history_l1_dropout.history['val_loss'], label='validation loss')
plt.xlabel('Epoch'); plt.ylabel('Loss'); plt.title('Scenario 2(e) — L1 + Dropout Loss'); plt.legend(); plt.show()

plt.figure(figsize=(7,4))
plt.plot(history_l1_dropout.history['acc'], label='training accuracy')
plt.plot(history_l1_dropout.history['val_acc'], label='validation accuracy')
plt.xlabel('Epoch'); plt.ylabel('Accuracy'); plt.title('Scenario 2(e) — L1 + Dropout Accuracy'); plt.legend(); plt.show()

"""### Ringkasan performance"""

import pandas as pd

def epochs_ran(history):
    return len(history.history['loss'])

def gap(history):
    # validation loss minus training loss, both at the last epoch actually run
    return history.history['val_loss'][-1] - history.history['loss'][-1]

results = pd.DataFrame({
    'Scenario': ['Baseline', 'L1', 'L2', 'Dropout', 'Early Stopping', 'L1 + Dropout'],
    'Test Loss': [loss, l1_loss, l2_loss, drop_loss, early_loss, l1d_loss],
    'Test Accuracy': [accuracy, l1_acc, l2_acc, drop_acc, early_acc, l1d_acc],
    'Epochs': [
        epochs_ran(history1), epochs_ran(history_l1), epochs_ran(history_l2),
        epochs_ran(history_dropout), epochs_ran(history_early), epochs_ran(history_l1_dropout),
    ],
    'Train-Val Loss Gap': [
        gap(history1), gap(history_l1), gap(history_l2),
        gap(history_dropout), gap(history_early), gap(history_l1_dropout),
    ],
})
results

"""## Kesimpulan

Dari kelima skenario yang diuji (10 epoch, arsitektur Flatten → Dense(64, relu) → Dense(10, softmax)) hasil test set-nya:

| Skenario         | Test Loss | Test Accuracy |
|------------------|-----------|----------------|
| Baseline         | 0.0871    | 97.42%         |
| L1 (rate=0.001)  | 0.5009    | 94.16%         |
| L2 (rate=0.001)  | 0.2469    | 96.70%         |
| Dropout (rate=0.5)| 0.1226   | 96.37%         |
| Early Stopping   | 0.0861    | 97.35%         |
| L1 + Dropout     | 0.4546    | 94.32%         |

**Baseline** menunjukkan tanda overfitting ringan: loss training terus turun sampai jauh di bawah loss validasi, sementara akurasi training mendekati 99% tapi validasi mentok di sekitar 97-98%.

**L1 (2a)** memberi dampak paling besar terhadap akurasi (94.24%) dibanding regularizer lain pada rate yang sama. Ini karena penalti L1 "menolkan" bobot secara agresif, sehingga dengan budget hanya 10 epoch, model belum sempat menyeimbangkan antara fit ke data dan memenuhi constraint L1-nya.

**L2 (2b)** memberi hasil paling stabil dari semua regularizer (96.87%), penalti kuadratiknya lebih halus dibanding L1, sehingga model tetap bisa konvergen dengan baik dalam epoch yang terbatas.

**Dropout (2c)** menurunkan akurasi lebih sedikit dibanding L1/L2 (96.38%), dengan pola khas: akurasi validasi justru lebih tinggi dari training selama proses training, karena dropout hanya aktif saat training (bukan saat evaluasi).

**Early Stopping (2d)** tidak pernah benar-benar terpicu dalam 10 epoch (loss validasi masih terus membaik), sehingga hasilnya mirip baseline (97.13%) — menunjukkan bahwa early stopping adalah mekanisme pengaman, bukan teknik yang otomatis meningkatkan performa.

**L1 + Dropout (2e)** memberi hasil terendah (94.26%) karena menggabungkan dua constraint sekaligus, model butuh lebih banyak epoch untuk mengoptimalkan performa di bawah beban regularisasi ganda ini.

**Catatan:** karena training neural network bersifat stokastik (bobot awal random, dropout mask random, urutan batch di-shuffle setiap epoch), angka di atas bisa berbeda tipis setiap kali notebook dijalankan ulang, namun pola dan urutan performa antar skenario tetap konsisten.

**Kesimpulan:** kekuatan regularisasi (rate L1/L2, tingkat dropout) harus disesuaikan dengan jumlah epoch yang tersedia. Regularisasi yang terlalu kuat relatif terhadap epoch yang sedikit justru menurunkan performa, bukan memperbaikinya.
"""